//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThoughtWorks.TreeSurgeon.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>go.bat\t\t\t\t\t,go.bat</string>\r\n  <string>Sapling.build\t\t\t,{0}.build</string>" +
            "\r\n  <string>Sapling.sln\t\t\t\t,src\\{0}.sln</string>\r\n  <string>RunAcceptanceTests.b" +
            "at\t,RunAcceptanceTests.bat</string>\r\n  <string>SaplingConsole.csproj\t,src\\{0}Con" +
            "sole\\{0}Console.csproj</string>\r\n  <string>AssemblyInfo.cs\t\t\t,src\\{0}Console\\Ass" +
            "emblyInfo.cs</string>\r\n  <string>HelloWorld.cs\t\t\t,src\\{0}Console\\HelloWorld.cs</" +
            "string>\r\n  <string>Core.csproj\t\t\t\t,src\\Core\\Core.csproj</string>\r\n  <string>Asse" +
            "mblyInfo.cs\t\t\t,src\\Core\\AssemblyInfo.cs</string>\r\n  <string>ApplicationInfo.cs\t\t" +
            ",src\\Core\\ApplicationInfo.cs</string>\r\n  <string>UnitTests.csproj\t\t,src\\UnitTest" +
            "s\\UnitTests.csproj</string>\r\n  <string>AssemblyInfo.cs\t\t\t,src\\UnitTests\\Assembly" +
            "Info.cs</string>\r\n  <string>TestApplicationInfo.cs\t,src\\UnitTests\\TestApplicatio" +
            "nInfo.cs</string>\r\n  <string>FitFixtures.csproj\t\t,src\\FitFixtures\\FitFixtures.cs" +
            "proj</string>\r\n  <string>AssemblyInfo.cs\t\t\t,src\\FitFixtures\\AssemblyInfo.cs</str" +
            "ing>\r\n  <string>TestFixture.cs\t\t\t,src\\FitFixtures\\TestFixture.cs</string>\r\n  <st" +
            "ring>FrontPage_content.txt\t\t\t,FitNesse\\FitNesseRoot\\FrontPage\\content.txt</strin" +
            "g>\r\n  <string>SaplingApplication_content.txt\t,FitNesse\\FitNesseRoot\\{0}Applicati" +
            "on\\content.txt</string>\r\n  <string>Suite_properties.xml\t\t\t,FitNesse\\FitNesseRoot" +
            "\\{0}Application\\properties.xml</string>\r\n  <string>SaplingSetUp_content.txt\t\t,Fi" +
            "tNesse\\FitNesseRoot\\{0}Application\\SetUp\\content.txt</string>\r\n  <string>Complet" +
            "edStories_content.txt\t,FitNesse\\FitNesseRoot\\{0}Application\\CompletedStories\\con" +
            "tent.txt</string>\r\n  <string>Suite_properties.xml\t\t\t,FitNesse\\FitNesseRoot\\{0}Ap" +
            "plication\\CompletedStories\\properties.xml</string>\r\n  <string>CurrentStories_con" +
            "tent.txt\t\t,FitNesse\\FitNesseRoot\\{0}Application\\CurrentStories\\content.txt</stri" +
            "ng>\r\n  <string>Suite_properties.xml\t\t\t,FitNesse\\FitNesseRoot\\{0}Application\\Curr" +
            "entStories\\properties.xml</string>\r\n  <string>FutureStories_content.txt\t\t,FitNes" +
            "se\\FitNesseRoot\\{0}Application\\FutureStories\\content.txt</string>\r\n  <string>Sui" +
            "te_properties.xml\t\t\t,FitNesse\\FitNesseRoot\\{0}Application\\FutureStories\\properti" +
            "es.xml</string>\r\n  <string>IterationOne_content.txt\t\t,FitNesse\\FitNesseRoot\\{0}A" +
            "pplication\\IterationOne\\content.txt</string>\r\n  <string>Suite_properties.xml\t\t\t," +
            "FitNesse\\FitNesseRoot\\{0}Application\\IterationOne\\properties.xml</string>\r\n  <st" +
            "ring>CurrentIteration_content.txt\t,FitNesse\\FitNesseRoot\\{0}Application\\CurrentI" +
            "teration\\content.txt</string>\r\n  <string>TestApplicationInfo_content.txt\t,FitNes" +
            "se\\FitNesseRoot\\{0}Application\\CompletedStories\\TestApplicationInfo\\content.txt<" +
            "/string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TemplateTree {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TemplateTree"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>coreGuid		,{GUID}</string>
  <string>unitTestGuid	,{GUID}</string>
  <string>consoleGuid	,{GUID}</string>
  <string>fitFixturesGuid	,{GUID}</string>
  <string>nantDeleteClause, ${directory::exists(build.dir)}</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VelocityContext {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VelocityContext"]));
            }
        }
    }
}
